### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by divadsn** [KwabenBerko/OpenWeatherMap-Android-Library#10]
We would like to give credit for the library in Lawnchair Launcher, but we can't find any `LICENSE` file in your repository or any related information in the readme.

Under what license is your work licensed?

**Comment by divadsn** [comment]
Related code for reference: https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/lawnchair/src/ch/deletescape/lawnchair/smartspace/OWMWeatherDataProvider.kt#L33-L36

**Comment by KwabenBerko** [comment]
> Under what license is your work licensed?

**MIT License**

Just added the` LICENSE `file to the GitHub repository.
Thank you very much for giving credit. Really appreciate it. ☺️

**Comment by divadsn** [comment]
Thank you a lot, we've included it now in our app :)

![grafik](https://user-images.githubusercontent.com/28547847/56462808-a50a4200-63c9-11e9-87e3-e084bd35e142.png)
