### ISSUE TITLE
Automatic Weather Updates Feature?

### ISSUE THREAD

**Issue by KwabenBerko** [KwabenBerko/OpenWeatherMap-Android-Library#12]
Hello everyone, 
Lately, I have been thinking of adding a new feature to the library because of [this issue](https://github.com/KwabenBerko/OpenWeatherMap-Android-Library/issues/8#issue-410604412): An Automatic Updates Feature. Wanted to find out from everyone if its a feature that would be beneficial to you.
Kindly let me know what you think.

**Comment by LeeDroid-** [comment]
I am just about to jump in and replace Google Awareness API weather data in my app, i would personally handle update's and update frequency my self in the background, any competent dev should be able to do this IMO. Going to start working on it tonight, your library looks very well organised and clean

**Comment by KwabenBerko** [comment]
> any competent dev should be able to do this IMO

Yeah, thats true 😄 .

> Going to start working on it tonight, your library looks very well organised and clean

Thank you very much!
