### ISSUE TITLE
5 day forecast

### ISSUE THREAD

**Issue by tefracky** [KwabenBerko/OpenWeatherMap-Android-Library#13]
In your README is a "5 day / 3 hour forecast" provided, but I can only see an example for a 3 hour forecast, so how can I use the 5 day forecast?

**Comment by KwabenBerko** [comment]
@tefracky 
Its actually a 3 hour forecast that spans 5 days.
In other words, there is forecast data at intervals of 3 hours within that 5 day period. 

[https://openweathermap.org/forecast5](https://openweathermap.org/forecast5)

**Comment by tefracky** [comment]
Thank you very much!
