### ISSUE TITLE
Sunrise/Sunset

### ISSUE THREAD

**Issue by LeeDroid-** [KwabenBerko/OpenWeatherMap-Android-Library#14]
Hi,

getSunrise() & getSunset() are returning the wrong values, it looks like you are getting the data in JSON format, I think these are only returned when using XML, can you confirm & is there a way to correct it?

**Comment by KwabenBerko** [comment]
Hello @LeeDroid- 
Sorry for the late reply. Thanks for bringing this to my notice.
The wrong values you receive for sunrise and sunset are due to a mishap on my end. Will be fixing this in a few days.

**Comment by KwabenBerko** [comment]
Hello @LeeDroid-
Sorry for the late reply. Just confirmed that sunrise and sunset values are also returned in JSON format. These values are also included in the [sample response data](https://samples.openweathermap.org/data/2.5/weather?id=2172797&appid=b6907d289e10d714a6e88b30761fae22) on OpenWeatherMap's API documentation's page.

What values are you getting for sunrise and sunset?

**Comment by LeeDroid-** [comment]
They are returning almost the same value, not relevant to location and only
a minute apart, quite strange

**Comment by KwabenBerko** [comment]
@LeeDroid- 
Were you able to resolve this?

**Comment by LeeDroid-** [comment]
Hi,

I haven't yet had time to re-visit it, its on my list now so i will let you know

**Comment by KwabenBerko** [comment]
Alright.
Great.
