### ISSUE TITLE
Didn't working in Release version of the app

### ISSUE THREAD

**Issue by shanu95** [KwabenBerko/OpenWeatherMap-Android-Library#15]
I had used this library and it is working great in debug mode. but when i create release version, it is crashing. it says java.lang.NullPointerException: throw with null exception in (SourceFile:299). Any idea why is that?

**Comment by LeeDroid-** [comment]
Probably Proguard, try excluding the classes provided by the library

**Comment by shanu95** [comment]
Yeah that is the problem. adding -keep class com.kwabenaberko.** {*;} fixed the issue. Thank you very much your library is awesome.

**Comment by LeeDroid-** [comment]
Not my library but I am a user of it, happy to help, it is great!
