### ISSUE TITLE
Read weather for next 5 days

### ISSUE THREAD

**Issue by geronimo69** [KwabenBerko/OpenWeatherMap-Android-Library#16]
How can read the weather for next 5 days?

I try to get the icon for each day using 

int icon = ThreeHourForecast.getList().get(i).getWeatherArray().get(0).getId().intValue();

 but icons codes are different for what I see on openweathermap site.

In same time when I use ThreeHourForecast.getList().get(i).getMain().getTempMin() or getTempMax() return different temperatures than openweathermap forcast page for same location.

**Comment by KwabenBerko** [comment]
@geronimo69 
Terribly sorry for the late response.
Will take a look at this issue over the weekend and get back to you.

**Comment by KwabenBerko** [comment]
@geronimo69 

Im not able to reproduce the issue. So far all the icon and temperature values I'm retrieving all seem to be accurate.

<img width="649" alt="Screen Shot 2019-12-04 at 11 25 22 PM" src="https://user-images.githubusercontent.com/13765161/70190571-265edc80-16ee-11ea-8aba-21bed9eb34d1.png">

The image above is from the open weather map site and the data below is from the library, which seems to be identical.(Note: OpenWeatherMap rounds temp max value on their site)
The icons are also accurate and can be retreived using this url : ```http://openweathermap.org/img/wn/ICON_GOES_HERE@2x.png```

```
Icon: 01n
Temp: 27.8
Temp Min: 27.8
Temp Max: 27.89
------------------------
Icon: 01n
Temp: 27.61
Temp Min: 27.61
Temp Max: 27.68
------------------------
Icon: 01d
Temp: 27.53
Temp Min: 27.53
Temp Max: 27.57
```

**Comment by KwabenBerko** [comment]
Closing as no response from OP.
Feel free to reopen.
