### ISSUE TITLE
Value  feels_like

### ISSUE THREAD

**Issue by ur5zeb** [KwabenBerko/OpenWeatherMap-Android-Library#18]
Hi! how to get the value feels _like?

**Comment by KwabenBerko** [comment]
Hi @ur5zeb,
This value was recently added and does not exist currently in the library.
It will be added though in the next release.

**Comment by ur5zeb** [comment]
thank you. When to expect a new release?

**Comment by KwabenBerko** [comment]
Hopefully, a week from now.

**Comment by KwabenBerko** [comment]
@ur5zeb 
I've been able to work on this issue. Kindly check it out and let me know what you think:

```gradle
implementation 'com.github.KwabenBerko:OpenWeatherMap-Android-Library:2.1.0-alpha'
```

**Comment by KwabenBerko** [comment]
Closing as no response from OP
Feel free to reopen.
