### ISSUE TITLE
Day or 12 hour forecast

### ISSUE THREAD

**Issue by Windsensor** [KwabenBerko/OpenWeatherMap-Android-Library#19]
Hi! 
Thanks for your library. I use it in my small project. Your library works fine. 
But I have one question: is it possible to somehow get the weather not for 3 hours, but for the whole day or 12 hours? 
For example, in the morning to see and know the weather at lunchtime and in the late afternoon.

**Comment by Windsensor** [comment]
Oops. Sorry I think I got it wrong.

getList() not only has 3 hours, but much more in 3 hour increments.

**Comment by KwabenBerko** [comment]
Hi @Windsensor , have you been able to resolve the issue?

**Comment by Windsensor** [comment]
Hi @KwabenBerko, yes. The case can be closed. Thanks again for the library.
