### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by Siddounet** [KwabenBerko/OpenWeatherMap-Android-Library#2]
Hi,
Nice lib ! But you didn't provide any support for language ?
Thx, BR, Bastien.

FYI : I added a PR https://github.com/KwabenBerko/OpenWeatherMap-Android-Library/pull/3

**Comment by KwabenBerko** [comment]
Thanks, Bastien!
Kindly follow the same pattern used for setting units.
eg:
helper.setLang(Lang.ENGLISH)

**Comment by Siddounet** [comment]
Done, I added all supported langs from OWM

**Comment by KwabenBerko** [comment]
Awesome!
