### ISSUE TITLE
Gson issue?

### ISSUE THREAD

**Issue by SpeedFire0** [KwabenBerko/OpenWeatherMap-Android-Library#5]
Hi! 
I can't figure out the source of this issue - is it on my side or on the library's?
I've recently migrated my project to AndroidX. Maybe this could cause this issue? (the weather works in emulator but not on real devices)

`09-08 00:30:23.922 31040 31040 V FCC_Service: updateWeather FAILURE = Unable to invoke no-args constructor for class e.f.a.b.a.a. Registering an InstanceCreator with Gson for this type may fix this problem.

09-08 00:30:23.922 31040 31040 W System.err: java.lang.RuntimeException: Unable to invoke no-args constructor for class e.f.a.b.a.a. Registering an InstanceCreator with Gson for this type may fix this problem.

09-08 00:30:23.922 31040 31040 W System.err: 	at com.google.gson.internal.ConstructorConstructor$14.a(ConstructorConstructor.java:228)

09-08 00:30:23.922 31040 31040 W System.err: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a(ReflectiveTypeAdapterFactory.java:212)

09-08 00:30:23.922 31040 31040 W System.err: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(ReflectiveTypeAdapterFactory.java:131)

09-08 00:30:23.922 31040 31040 W System.err: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.a(ReflectiveTypeAdapterFactory.java:222)

09-08 00:30:23.922 31040 31040 W System.err: 	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)

09-08 00:30:23.922 31040 31040 W System.err: 	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)

09-08 00:30:23.922 31040 31040 W System.err: 	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)

09-08 00:30:23.922 31040 31040 W System.err: 	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)

09-08 00:30:23.922 31040 31040 W System.err: 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)

09-08 00:30:23.932 31040 31040 W System.err: 	at com.google.firebase.perf.network.zzg.onResponse(Unknown Source)

09-08 00:30:23.932 31040 31040 W System.err: 	at i.H$a.b(RealCall.java:153)

09-08 00:30:23.932 31040 31040 W System.err: 	at i.a.b.run(NamedRunnable.java:32)

09-08 00:30:23.932 31040 31040 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

09-08 00:30:23.932 31040 31040 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

09-08 00:30:23.932 31040 31040 W System.err: 	at java.lang.Thread.run(Thread.java:841)

09-08 00:30:23.932 31040 31040 W System.err: Caused by: java.lang.UnsupportedOperationException: Abstract class can't be instantiated! Class name: e.f.a.b.a.a

09-08 00:30:23.932 31040 31040 W System.err: 	at com.google.gson.internal.UnsafeAllocator.a(UnsafeAllocator.java:120)

09-08 00:30:23.932 31040 31040 W System.err: 	at com.google.gson.internal.UnsafeAllocator$1.b(UnsafeAllocator.java:49)

09-08 00:30:23.932 31040 31040 W System.err: 	at com.google.gson.internal.ConstructorConstructor$14.a(ConstructorConstructor.java:225)

09-08 00:30:23.932 31040 31040 W System.err: 	... 14 more`

**Comment by SpeedFire0** [comment]
Looks like something related to this SO question: https://stackoverflow.com/questions/51459340/retrofit-2-0-gson-android-unable-to-invoke-no-args-constructor-for-interfac

**Comment by KwabenBerko** [comment]
Yes. its likely an issue with Gson. 
What are you trying to do? 
Can I see that portion of your code?

**Comment by SpeedFire0** [comment]
Hi!
This is just a normal weather request (which worked fine before transition to AndroidX)

`sPrefDefEditor.putString(WEATHER_LAST_UPDATE_ICON_ID, "updating");
                    sPrefDefEditor.putString(WEATHER_LAST_TEMPERATURE, "-");
                    sPrefDefEditor.apply();
                    double last_lat = 0;
                    double last_lon = 0;
                    try {
                        last_lat = Double.parseDouble(sPrefDef.getString(LAST_LATITUDE, ""));
                        last_lon = Double.parseDouble(sPrefDef.getString(LAST_LONGITUDE, ""));
                    } catch (Exception e){}
                    Log.d(LOG_TAG, "updateWeather DO update. Passed mins = " + (System.currentTimeMillis() - sPrefDef.getLong(WEATHER_LAST_UPDATE_TIME, 0)) / 60000 + ", last_lat = " + last_lat +","+last_lon + ", weatherHelper = " + (weatherHelper == null ? "null" : "not null"));

                    if (weatherHelper != null && last_lat != 0 && last_lon != 0) {
                        Log.d(LOG_TAG, "updateWeather DO2 update. Passed mins = " + (System.currentTimeMillis() - sPrefDef.getLong(WEATHER_LAST_UPDATE_TIME, 0)) / 60000);

                        weatherHelper.getCurrentWeatherByGeoCoordinates(last_lat, last_lon, new OpenWeatherMapHelper.CurrentWeatherCallback() {
                            @Override
                            public void onSuccess(CurrentWeather currentWeather) {
                                Log.d(LOG_TAG, "updateWeather Success");
                                Log.v(LOG_TAG,
                                        "updateWeather Coordinates: " + currentWeather.getCoord().getLat() + ", " + currentWeather.getCoord().getLon() + "\n"
                                                + "Weather Description: " + currentWeather.getWeatherArray().get(0).getDescription() + "\n"
                                                + "Max Temperature: " + currentWeather.getMain().getTempMax() + "\n"
                                                + "Current Temp: " + currentWeather.getMain().getTemp() + "\n"
                                                + "Wind Speed: " + currentWeather.getWind().getSpeed() + "\n"
                                                + "City, Country: " + currentWeather.getName() + ", " + currentWeather.getSys().getCountry() + "\n"
                                                + "Weather Icon: " + currentWeather.getWeatherArray().get(0).getIcon() + "\n"
                                );
                                String result = String.format("%.0f", currentWeather.getMain().getTemp());
                                String tempString = result + "°";
                                sPrefDefEditor.putString(WEATHER_LAST_UPDATE_ICON_ID, currentWeather.getWeatherArray().get(0).getIcon());
                                sPrefDefEditor.putString(WEATHER_LAST_TEMPERATURE, tempString);
                                sPrefDefEditor.putLong(WEATHER_LAST_UPDATE_TIME, System.currentTimeMillis());
                                sPrefDefEditor.apply();
                                updateWeatherUniversal(context);
                            }

                            @Override
                            public void onFailure(Throwable throwable) {
                                sPrefDefEditor.putString(WEATHER_LAST_UPDATE_ICON_ID, "updating");
                                sPrefDefEditor.putString(WEATHER_LAST_TEMPERATURE, "-");
                                sPrefDefEditor.apply();
                                Log.v(LOG_TAG, "updateWeather FAILURE = " + throwable.getMessage());
                                throwable.printStackTrace();
                                updateWeatherUniversal(context);
                            }
                        });

                    }`

**Comment by KwabenBerko** [comment]
Terribly sorry about the delayed response.
I'll test this on AndroidX and get back to you.

**Comment by KwabenBerko** [comment]
Hi @SpeedFire0 
Have you been able to fix this issue?
I just recently got some free time and I've been able to test on AndroidX. 
I'm not having any issues though.

**Comment by SpeedFire0** [comment]
> Hi @SpeedFire0
> Have you been able to fix this issue?

Yes. Kind of. I found out that the real issue is a ProGuard (minifyEnabled true). I added your library to exception from ProGuard rules so it is not obfuscated now. This fixed the issue.
I assume that the real issue is still there (and it relates to Gson). But I don't know why it only appears after obfuscation.

**Comment by KwabenBerko** [comment]
Alright.
Thats good to know. 

> I assume that the real issue is still there (and it relates to Gson). But I don't know why it only appears after obfuscation

Yh weird.
