### ISSUE TITLE
Getting data on precipitation

### ISSUE THREAD

**Issue by guyhatzav** [KwabenBerko/OpenWeatherMap-Android-Library#7]
Hello,
The library you wrote is simply wonderful :)
I just wanted to ask,
how can I get the data on precipitation out of the weather forecast (value, unit and type)?

Thx in advance :)

**Comment by KwabenBerko** [comment]
Hi @guyhatzav , Thanks for the kind words and for pointing this out. Guess I missed it 🤦‍♂️. Ill be adding that in the next release which will be in the next few days. 
Stay tuned :)

**Comment by KwabenBerko** [comment]
Hi, @guyhatzav, check out the latest release.

**Comment by guyhatzav** [comment]
you're greattt!! thank you so much :) :)
