### ISSUE TITLE
weather auto update

### ISSUE THREAD

**Issue by hardcorelolo** [KwabenBerko/OpenWeatherMap-Android-Library#8]
Does the weather update from OpenWeatherMap automatically in this library? Or do I need to implement something from my end? Thanks

**Comment by blakematis** [comment]
> Does the weather update from OpenWeatherMap automatically in this library? Or do I need to implement something from my end? Thanks

This library requires you to make the requests yourself. So yes you would need to repeatedly make the calls for Current Conditions or 3 hour forecasts yourself through some type of service.

**Comment by KwabenBerko** [comment]
@blakematis @hardcorelolo 
Exactly.
