### ISSUE TITLE
Targeting targetSdkVersion 28 prevents weather from showing

### ISSUE THREAD

**Issue by hardcorelolo** [KwabenBerko/OpenWeatherMap-Android-Library#9]
Hey when i target sdk version 28 within my app....openweatherhelper does not show the weather within my app, i get no errors.

i must target sdk version 27 or lower in order for your library to work and i do not why this happens.

Thanks

**Comment by KwabenBerko** [comment]
Are you using the latest version?

**Comment by hardcorelolo** [comment]
Sorry about the delay...Yes im currently using 2.0.1


implementation 'com.github.KwabenBerko:OpenWeatherMap-Android-Library:2.0.1'

**Comment by KwabenBerko** [comment]
@hardcorelolo  Okay, no problem
Sorry for the delay in reply too. Ive been very busy these last few weeks. Will be going through this issue this weekend and give you some feedback soon. 
Thank you

**Comment by KwabenBerko** [comment]
@hardcorelolo 
Kindly check this alpha release :
 `implementation "com.github.KwabenBerko:OpenWeatherMap-Android-Library:2.0.2-alpha"`
 and let me know if your issue has been resolved.
Thank you for your patience.

**Comment by hardcorelolo** [comment]
Hey sorry about the delay again...yes it works now with 2.0.2-alpha! good job and thank you for fixing it...should i use this library or wait till its an official release? thanks again

**Comment by KwabenBerko** [comment]
@hardcorelolo You can now use the official release: 
`implementation "com.github.KwabenBerko:OpenWeatherMap-Android-Library:2.0.2"`

**Comment by hardcorelolo** [comment]
Thanks for your help...all is good!
